version: '3.8'

services:
  db:
    image: 'mysql:8'
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '${MYSQL_PORT_LOCAL_TO_CONTAINER}:${MYSQL_PORT_CONTAINER}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory_net

  redis:
    image: 'redis:7'
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT_LOCAL_TO_CONTAINER}:${REDIS_PORT_CONTAINER}'
    networks:
      - inventory_net

  backend:
    image: 'bashirjanbalat/inventory_app_be:latest'
    container_name: app_be
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - '${APP_PORT_LOCAL_TO_CONTAINER}:${APP_PORT_CONTAINER}'
    networks:
      - inventory_net

  frontend:
    image: 'bashirjanbalat/inventory_app_fe:latest'
    container_name: app_fe
    depends_on:
      - db
      - redis
      - backend
    env_file:
      - .env
    ports:
      - '${APP_FRONT_PORT_LOCAL_TO_CONTAINER}:${APP_FRONT_PORT_CONTAINER}'
    networks:
      - inventory_net

volumes:
  mysql_data:

networks:
  inventory_net:
    driver: bridge
